repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      exclude: ^tests/
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
        language_version: python2.7
    -   id: check-merge-conflict
    -   id: flake8
        language_version: python2.7
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.670
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --py2, --follow-imports=skip]
        language_version: python3.6
        exclude: ^tests/
