
language: python
python: "3.6"

sudo: required
cache: pip
dist: xenial

matrix:
  include:
    - python: "3.6"
      before_script:
        - sudo apt update && sudo apt install -y protobuf-compiler
        - sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
        - git submodule update --init --recursive
        - pip install -r requirements_dev.txt
        - python setup.py build_pbf
        - pip install -r requirements_pre-commit.txt
        - pre-commit install
      script:
        - pre-commit run --all --show-diff-on-failure

