
language: python
python: "3.6"
sudo: required
cache: pip
dist: xenial

matrix:
  include:  # This script is triggered only with python3.6
    - python: "3.6"
      before_script:
        - pip install -r requirements_pre-commit.txt
        - pip install pre-commit
        - pre-commit install
      script:
        - pre-commit run --all --show-diff-on-failure

